config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  resources :weather_forecasts, except: %i[destroy edit update] do
    member do
      get :extended
    end
  end

  # Defines the root path route ("/")
  root 'weather_forecasts#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/location.rb
# frozen_string_literal: true

# A model that represents a location
class Location
  include ActiveModel::API

  attr_accessor :location

  validates :location, presence: true
  validate :zip_code_or_state?

  def zip_code?
    location.to_s.match?(/\A\d{5}\z/)
  end

  def city_state?
    location.to_s.match?(/\A[A-Za-z\s]+,\s[A-Za-z]{2}\z/)
  end

  def city_state
    return location if city_state?
    return unless zip_code?

    ZipCodes.identify(location).values_at(:city, :state_code).join(', ')
  end

  def zip_code
    return location if zip_code?
  end

  def zip_code_or_state?
    return false unless location

    zip_code? || city_state?
  end
end

app/models/tomorrow_io.rb
# frozen_string_literal: true

require 'uri'
require 'net/http'

API_KEY = 'osJ5n2tnu3ntYIoWF6PMTTxPL8gDU8Xc'

# A class that handles retrieving weather forecasts from the Tomorrow.io API
class TomorrowIo
  attr_reader :location, :extended_forecast

  def initialize(location, extended_forecast: false)
    @location = CGI.escape(location)
    @extended_forecast = extended_forecast
  end

  alias extended_forecast? extended_forecast

  def base_url
    'https://api.tomorrow.io/v4/weather'
  end

  def forecast_url
    "#{base_url}/forecast?location=#{location}&timesteps=1d&apikey=#{API_KEY}"
  end

  def realtime_url
    "#{base_url}/realtime?location=#{location}&apikey=#{API_KEY}"
  end

  def url
    @url ||= URI(extended_forecast? ? forecast_url : realtime_url)
  end

  def http
    Net::HTTP.new(url.host, url.port).tap do |net|
      net.use_ssl = true
    end
  end

  def request
    Net::HTTP::Get.new(url).tap do |r|
      r['accept'] = 'application/json'
    end
  end

  # memoize the response so that multiple requests are not made
  def response
    @response ||= http.request(request)
  end

  def body
    response.read_body
  end

  def successful?
    response.code == '200'
  end
end

app/models/weather_forecast.rb
# frozen_string_literal: true

# A model that represents a weather forecast for a given location
class WeatherForecast < ApplicationRecord
  # A forecast for a particular location is cached
  # as a JSON string in Redis
  kredis_json :realtime_forecast
  kredis_json :extended_forecast

  geocoded_by :location

  after_validation :geocode

  validates :location, presence: { message: 'must be a valid city and state combination, or zipcode' }

  def current_forecast
    @current_forecast ||= TomorrowIo.new(to_coordinates.join(', '))
  end

  def current_extended_forecast
    @current_extended_forecast ||= TomorrowIo.new(to_coordinates.join(', '), extended_forecast: true)
  end

  def temperature(scale=:fahrenheit)
    return 0.0 unless realtime_forecast.value
    temp = JSON.parse(realtime_forecast.value).dig('data', 'values', 'temperature')
    return temp if scale == :celcius

    (temp * 9 / 5) + 32
  end

  def update_forecast!
    Rails.cache.fetch("weather_forecast:#{location}:realtime", expires_in: 30.minutes) do
      realtime_forecast.value = current_forecast.body if current_forecast.successful?
    end
  end

  def update_extended_forecast!
    Rails.cache.fetch("weather_forecast:#{location}:extended", expires_in: 30.minutes) do
      extended_forecast.value = current_extended_forecast.body if current_extended_forecast.successful?
    end
  end

  def daily_extended_forecast
    JSON.parse(extended_forecast.value).dig('timelines', 'daily')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/weather_forecasts_controller.rb
# frozen_string_literal: true

# A controller that handles retrieving weather forecasts
class WeatherForecastsController < ApplicationController
  def create
    @weather_forecast = WeatherForecast.find_or_initialize_by(
      location: location.city_state
    )

    if @weather_forecast.save
      @weather_forecast.update_forecast!
      redirect_to @weather_forecast
    else
      render :new, status: 422
    end
  end

  def show
    @weather_forecast = WeatherForecast.find(params[:id])
    @weather_forecast.update_forecast!
  end

  def extended
    @weather_forecast = WeatherForecast.find(params[:id])
    @weather_forecast.update_extended_forecast!
  end

  private

  def location
    @location ||= Location.new(location: weather_forecast_params[:location])
  end

  def weather_forecast_params
    params.require(:weather_forecast).permit(:location)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Realtime Weather</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/weather_forecasts/_realtime_forecast.html.erb
<dl>
  <dt>Temperature</dt>
  <dd><%= @weather_forecast.temperature(scale=:celcius).round %> C</dd>
  <dd><%= @weather_forecast.temperature.round %> F</dd>
</dl>

<p>
  Cached?
  <% if Rails.cache.exist?("weather_forecast:#{@weather_forecast.location}:realtime") %>
    <span>Yes</span>
  <% else %>
    <b style="color: red;">No</b>
  <% end %>
</p>

app/views/weather_forecasts/extended.html.erb
<h1><%= @weather_forecast.location %></h1>

<%= render partial: "realtime_forecast" %>

<dl>
  <% @weather_forecast.daily_extended_forecast.each do |daily_forecast| %>
    <dt>
      <%= time_tag daily_forecast.dig('time').to_date %>
    </dt>
    <dd>Low: <%= daily_forecast.dig('values', 'temperatureMin') %></dd>
    <dd>High: <%= daily_forecast.dig('values', 'temperatureMax') %></dd>
  <% end %>
</dl>

<%= link_to 'New Search', new_weather_forecast_path %>

app/views/weather_forecasts/new.html.erb
<h1>Weather Forecast</h1>

<div>
  <% if @weather_forecast && @weather_forecast.errors.any? %>
    <ul>
      <% @weather_forecast.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
</div>

<div>
  <%= form_with scope: :weather_forecast, url: weather_forecasts_path do |f| %>
    <div>
      <%= f.label :location %>
      <%= f.text_field :location %>
    </div>
    <div>
      <%= f.submit "Get Forecast" %>
    </div>
  <% end %>
</div>

app/views/weather_forecasts/show.html.erb
<h1><%= @weather_forecast.location %></h1>

<%= render partial: "realtime_forecast" %>

<%= link_to 'Extended Forecast', extended_weather_forecast_path(@weather_forecast) %> | 
<%= link_to 'New Search', new_weather_forecast_path %>